adding the larsoftobj suite

diff --git a/build_tools/cp-lar-tag b/build_tools/cp-lar-tag
--- a/build_tools/cp-lar-tag
+++ b/build_tools/cp-lar-tag
@@ -14,6 +14,7 @@
 # n's product_list must set up package n+1.
 declare -a packages=(larana larreco larsim  larevt lardata larcore)
 declare -a extra_packages=(lareventdisplay larexamples larpandora)
+declare -a obj_packages=(larsim lardata larcore)
 # Tag message.
 tag_msg='LArSoft suite cross-package tag'
 
@@ -127,4 +128,38 @@ while [[ -n "$1" ]]; do
     ensure_gitconfig $package
     ptag "${package}" "LARSOFT_SUITE_${larsoft_version}" "${pv}"
   done
+  
+  # larpandoracontent
+  last_pkg=larpandora
+  package=larpandoracontent
+  product=`product_for "$package"`
+  pv=`wget --no-check-certificate -q -O - "https://cdcvs.fnal.gov/redmine/projects/${last_pkg}/repository/raw/ups/product_deps?rev=LARSOFT_SUITE_${larsoft_version}" | \
+   grep    -e '^[ 	]*'"$product"'[ 	]\{1,\}' | \
+   sed -e 's/^[ 	]*'"$product"'[ 	]\{1,\}\(v[^ 	]*\).*$/\1/'`
+  if [[ -n "$pv" ]]; then
+    echo "Found $package tag $pv corresponding to LArSoft tag $larsoft_version."
+  else
+    echo "Could not find tag for package $package corresponding to LArSoft tag $larsoft_version." 1>&2
+    continue
+  fi
+  ensure_gitconfig $package
+  ptag "${package}" "LARSOFT_SUITE_${larsoft_version}" "${pv}"
+  
+  # larsoftobj packages
+  for last_pkg in "${obj_packages[@]}"; do
+    package=${last_pkg}obj
+    product=`product_for "$package"`
+    pv=`wget --no-check-certificate -q -O - "https://cdcvs.fnal.gov/redmine/projects/${last_pkg}/repository/raw/ups/product_deps?rev=LARSOFT_SUITE_${larsoft_version}" | \
+     grep    -e '^[ 	]*'"$product"'[ 	]\{1,\}' | \
+     sed -e 's/^[ 	]*'"$product"'[ 	]\{1,\}\(v[^ 	]*\).*$/\1/'`
+    if [[ -n "$pv" ]]; then
+      echo "Found $package tag $pv corresponding to LArSoft tag $larsoft_version."
+    else
+      echo "Could not find tag for package $package corresponding to LArSoft tag $larsoft_version." 1>&2
+      continue
+    fi
+    ensure_gitconfig $package
+    ptag "${package}" "LARSOFT_SUITE_${larsoft_version}" "${pv}"
+  done
+
 done
