create an arbitrarily named branch

diff --git a/build_tools/tagLAr b/build_tools/tagLAr
--- a/build_tools/tagLAr
+++ b/build_tools/tagLAr
@@ -24,10 +24,12 @@ fullCom="${thisComFull%.*}"
 function usage() {
     echo "Usage: $fullCom <start|update|tag|merge> <tag>"
     echo "Usage: $fullCom patch <new tag> <existing tag>"
+    echo "Usage: $fullCom branch <new branch> <existing tag>"
     echo "Usage: $fullCom mkdir <new tag> <working_dir>"
     echo "   mkdir  - mkdir <working_dir>/<tag>, run newDev, and checkout larsoft_suite, uboone, and lbnecode"
     echo "   start - create release/<tag> branch"
     echo "   patch - create release/<tag> branch based on existing tag"
+    echo "   branch - create <branch> branch based on existing tag"
     echo "   update - modify product_deps to use <tag>"
     echo "   tag - merge changes with master and tag"
     echo "   merge - merge changes with develop"
@@ -158,6 +160,23 @@ then
      cd ${MRB_SOURCE}/${REP}
      git checkout ${oldtag}
      git checkout -b release/${tag}
+     okflow=$?
+     if [ ! ${okflow} ]
+     then
+	echo "${REP} git flow failure: ${okflow}"
+	exit 1
+     fi
+  done
+fi
+
+if [ "${flow}" = "branch" ]
+then
+  oldtag=$3
+  for REP in $pkglist
+  do
+     cd ${MRB_SOURCE}/${REP}
+     git checkout ${oldtag}
+     git checkout -b ${tag}
      okflow=$?
      if [ ! ${okflow} ]
      then
