add e17

diff --git a/build_tools/tagLAr b/build_tools/tagLAr
--- a/build_tools/tagLAr
+++ b/build_tools/tagLAr
@@ -68,11 +68,14 @@ create_working_directory() {
   fi
   mkdir -p ${working_dir}/${tag} || { echo "ERROR: failed to create ${working_dir}/${tag}"; exit 1; }
   mkdir -p ${working_dir}/${tag}/p  ${working_dir}/${tag}/d || { echo "ERROR: failed to create ${working_dir}/${tag}/p"; exit 1; }
+  mkdir -p ${working_dir}/${tag}/e17p  ${working_dir}/${tag}/e17d || { echo "ERROR: failed to create ${working_dir}/${tag}/e17p"; exit 1; }
   mkdir -p ${working_dir}/${tag}/c2p  ${working_dir}/${tag}/c2d || { echo "ERROR: failed to create ${working_dir}/${tag}/c2p"; exit 1; }
   cd ${working_dir}/${tag}
   echo "run mrb newDev"
   mrb newDev -f -v ${tag} -q e15:prof -T p || exit 1
   mrb newDev -f -v ${tag} -q e15:debug -T d || exit 1
+  mrb newDev -f -v ${tag} -q e17:prof -T e17p || exit 1
+  mrb newDev -f -v ${tag} -q e17:debug -T e17d || exit 1
   mrb newDev -f -v ${tag} -q c2:prof -T c2p || exit 1
   mrb newDev -f -v ${tag} -q c2:debug -T c2d || exit 1
   echo "source localProductsXXX/setup"
