smart clone options

diff --git a/build_tools/tagLAr b/build_tools/tagLAr
--- a/build_tools/tagLAr
+++ b/build_tools/tagLAr
@@ -86,6 +86,8 @@ create_working_directory() {
   mrb g larutils
   echo "checkout larpandoracontent"
   mrb g larpandoracontent
+  # look for extra options 
+  if [ -z "${extra_options}" ]; then
   echo "checkout dunetpc"
   mrb g dunetpc
   echo "checkout duneutil"
@@ -98,12 +100,37 @@ create_working_directory() {
   mrb g sbndcode
   mrb g sbndutil
   echo "checkout uboonecode"
-  mrb g uboonecode
+  mrb  g uboonecode
   mrb g ubutil
   echo "checkout argoneutcode"
   mrb g argoneutcode
   ##echo "checkout icaruscode"
   ##mrb g icaruscode
+  elif [[ ${extra_options} == "argoneut" ]]; then
+  echo "checkout argoneutcode"
+  mrb g argoneutcode
+  elif [[ ${extra_options} == "dune" ]]; then
+  echo "checkout dunetpc"
+  mrb g dunetpc
+  echo "checkout duneutil"
+  mrb g duneutil
+  elif [[ ${extra_options} == "lariat" ]]; then
+  echo "checkout lariatsoft"
+  mrb g lariatsoft
+  mrb g -d lariatfragments lariat-online-lariatfragments
+  mrb g -d lariatutil lardbt-lariatutil
+  elif [[ ${extra_options} == "sbnd" ]]; then
+  echo "checkout sbndcode"
+  mrb g sbndcode
+  mrb g sbndutil
+  elif [[ ${extra_options} == "uboone" ]]; then
+  echo "checkout uboonecode"
+  mrb  g uboonecode
+  mrb g ubutil
+  else
+    echo "ERROR: unrecognized option ${extra_options}"
+    exit 1
+  fi
 }
 
 # Determine command options (just -h for help)
@@ -119,6 +146,7 @@ done
 flow=${1}
 tag=${2}
 extra=${3}
+extra_options=${4}
 if [ -z "${flow}" ]
 then
     echo 'ERROR: no options specified'
