First complete version

diff --git a/cvmfs/oasis-sync b/cvmfs/oasis-sync
--- a/cvmfs/oasis-sync
+++ b/cvmfs/oasis-sync
@@ -1,1 +1,118 @@
 #!/bin/bash
+# Sync files from /grid/fermiapp/products to oasis
+# Written by Dave Dykstra
+
+ME="`basename $0`"
+usage()
+{
+    echo "$ME [-nvrp] <path_under_/grid/fermiapp/products>" >&2
+    echo "  -n: use the rsync dry-run option (implies -r)" >&2
+    echo "  -v: use the rsync verbose option" >&2
+    echo "  -r: do only rsync step" >&2
+    echo "  -p: do only publish step" >&2
+    echo "If both -r and -p are given, both will be done (same as the default)" >&2
+    echo "  except if the rsync step has an error, the publish will be skipped." >&2
+    exit 1;
+}
+
+RSYNCOPTS=""
+DORSYNC=""
+DOPUBLISH=""
+while getopts nvrp flag; do
+    case $flag in
+	n) RSYNCOPTS="$RSYNCOPTS -$flag"; DORSYNC=true;;
+	v) RSYNCOPTS="$RSYNCOPTS -$flag";;
+	r) DORSYNC=true;;
+	p) DOPUBLISH=true;;
+	?) usage;;
+    esac
+done
+shift $(( OPTIND - 1 ))
+
+if [ -z "$DORSYNC" ]; then
+    if [ -z "$DOPUBLISH" ]; then
+	# default is to do both
+	DORSYNC=true
+	DOPUBLISH=true
+    else
+	DORSYNC=false
+    fi
+elif [ -z "$DOPUBLISH" ]; then
+    DOPUBLISH=false
+fi
+
+if [ $# != 1 ] || [ -z "$1" ]; then
+    usage
+fi
+
+PRODUCTS="$1"
+
+if [ ! -d "/grid/fermiapp/products/$PRODUCTS" ]; then
+    echo "/grid/fermiapp/products/$PRODUCTS does not exist" >&2
+    exit 1
+fi
+
+DESTPRODUCT="${PRODUCTS%%/*}"
+case "$DESTPRODUCT" in
+    "") echo "$ME: destination path may not start with '/'" >&2
+	exit 1
+	;;
+    common|larsoft)
+	VO=fermilab
+	;;
+    *)	VO="$DESTPRODUCT"
+	;;
+esac
+
+PROXYVO="`voms-proxy-info -all|awk '{if ($1 == "VO"){print $3}}'`"
+
+if [ -z "$PROXYVO" ]; then
+    echo "$ME: did you do \"voms-proxy-init -voms $VO\"?" >&2
+    exit 1
+fi
+
+if [ "$VO" != "$PROXYVO" ]; then
+    echo "$ME: voms proxy VO \"$PROXYVO\" does not match expected VO \"$VO\"" >&2
+    exit 1
+fi
+
+if voms-proxy-info -all|grep -q "timeleft.*: 0:00:00"; then
+    echo "$ME: voms proxy expired, run voms-proxy-init again" 2>&1
+    exit 1
+fi
+
+GSISSH="gsissh -o GSSAPIDelegateCredentials=yes"
+HOST="ouser.$VO@oasis-login.opensciencegrid.org"
+DIR="/net/nas01/Public/ouser.$VO/products"
+
+if ! $GSISSH $HOST test -d $DIR/$DESTPRODUCT; then
+    echo "$ME: cannot see destination directory $DIR/$DESTPRODUCT on $HOST" >&2
+    exit 2
+fi
+
+EXCLUDE=""
+while [ "${PRODUCTS%/}" != "${PRODUCTS}" ]; do
+    # remove trailing slashes because they mess up exclude path calculation
+    PRODUCTS="${PRODUCTS%/}"
+done
+case "$PRODUCTS" in
+    */*/*) ;;
+    */*) EXCLUDE="--exclude /nightly/ --exclude /nightly.version/";;
+    *)   EXCLUDE="--exclude /*/nightly/ --exclude /*/nightly.version/";;
+esac
+
+RET=0
+if $DORSYNC; then
+    (set -x;time rsync -e "$GSISSH" -aW $RSYNCOPTS --delete $EXCLUDE --stats /grid/fermiapp/products/$PRODUCTS/ "$HOST:$DIR/$PRODUCTS/")
+    RET=$?
+    if [ "$RET" != 0 ]; then
+	DOPUBLISH=false
+    fi
+fi
+
+if $DOPUBLISH; then
+    (set -x; time $GSISSH $HOST osg-oasis-update)
+    RET=$?
+fi
+
+exit $RET
